### PR TITLE
ci: remove auto generated docs line with current date

### PR DESCRIPTION
**Pull request by froblesmartin**
Right now the CI will fail with any new PR due to the change in the date.

To avoid it, I propose to remove that generated line with the feature flag of the generator.

### CODE REVIEW

**Comment by jackwotherspoon** [comment]
Can confirm this worked for the Cloud SQL builds: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/actions/runs/12182514848/job/33981712140?pr=2342

nit: @froblesmartin I think this PR should probably be a `docs:` or `ci:` prefix, we normally reserve `fix:` for a bug fix that touched production code. 😄 

Thanks again! 👍

**Comment by froblesmartin** [comment]
> Can confirm this worked for the Cloud SQL builds: https://github.com/GoogleCloudPlatform/cloud-sql-proxy/actions/runs/12182514848/job/33981712140?pr=2342
> 
> nit: @froblesmartin I think this PR should probably be a `docs:` or `ci:` prefix, we normally reserve `fix:` for a bug fix that touched production code. 😄
> 
> Thanks again! 👍

You are welcome! 😄  I have changed the PR title. Will you squash or should I amend the commit too? 🤔

**Comment by jackwotherspoon** [comment]
> You are welcome! 😄 I have changed the PR title. Will you squash or should I amend the commit too? 🤔

We will squash so no need to amend 😄

**Review by enocom — APPROVED** [review]
Thank you!

**Pull request merged**
